### ISSUE TITLE
Some links in the navigation bar are not working

### ISSUE THREAD

**Issue by samuelgp** [CS108FinalProject/QuizWebsite#15]
My Messages and Homepage.

![image](https://cloud.githubusercontent.com/assets/11142434/6519394/13d943ae-c368-11e4-9bf9-e0ac1d51dec9.png)

![image](https://cloud.githubusercontent.com/assets/11142434/6519398/22513036-c368-11e4-9c32-418af0c10fbe.png)

**Comment by gamdur** [comment]
Homepage works now.

**Comment by christky** [comment]
Fixed..homepage was missing a close bracket <th      ">"

Messages is not a link, it is a heading. Associated with the selection tab which will tell you which messages to display. Their correspondence should be handled by css styling
