### ISSUE TITLE
Admin taken to non admin page

### ISSUE THREAD

**Issue by samuelgp** [CS108FinalProject/QuizWebsite#16]
guy4 is an admin, at login point he is taken to the admin homepage, but if I go to another page, like looking up a user, and then go back to the homepage, I'm taken to a non admin page. An admin should never go to a non admin page unless he/she is demoted.

![image](https://cloud.githubusercontent.com/assets/11142434/6519508/d26bc264-c369-11e4-9429-f78865d7b693.png)

**Comment by gamdur** [comment]
Try to pull, it's working for me.
