### ISSUE TITLE
Not getting friend requests

### ISSUE THREAD

**Issue by samuelgp** [CS108FinalProject/QuizWebsite#17]
Sent a friend request from notadmin to guy4, guy 4 didn't get a notification.

**Comment by gamdur** [comment]
Fixed it. I got the following when I tried to unfriend guy4 twice:
java.lang.RuntimeException: Problem executing query: SELECT * FROM Accounts WHERE userName = "guy4"
	com.dbinterface.Database.getValues(Database.java:680)
	com.accounts.Account.<init>(Account.java:64)
	com.accounts.AccountManager.getAccount(AccountManager.java:75)
	com.accounts.pages.SendMessageServlet.doPost(SendMessageServlet.java:53)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:646)
	javax.servlet.http.HttpServlet.service(HttpServlet.java:727)
	org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:52)

**Comment by samuelgp** [comment]
Looking into it

**Comment by gamdur** [comment]
Fixed.
